In [7]:
from torchvision import transforms
from PIL import Image
from torch.utils.tensorboard import SummaryWriter

In [8]:
writer = SummaryWriter()

In [6]:
img = Image.open("Dataset/train/ants/0013035.jpg")
trans_totensor = transforms.ToTensor()
img_tensor = trans_totensor(img)
img_tensor

tensor([[[0.3137, 0.3137, 0.3137,  ..., 0.3176, 0.3098, 0.2980],
         [0.3176, 0.3176, 0.3176,  ..., 0.3176, 0.3098, 0.2980],
         [0.3216, 0.3216, 0.3216,  ..., 0.3137, 0.3098, 0.3020],
         ...,
         [0.3412, 0.3412, 0.3373,  ..., 0.1725, 0.3725, 0.3529],
         [0.3412, 0.3412, 0.3373,  ..., 0.3294, 0.3529, 0.3294],
         [0.3412, 0.3412, 0.3373,  ..., 0.3098, 0.3059, 0.3294]],

        [[0.5922, 0.5922, 0.5922,  ..., 0.5961, 0.5882, 0.5765],
         [0.5961, 0.5961, 0.5961,  ..., 0.5961, 0.5882, 0.5765],
         [0.6000, 0.6000, 0.6000,  ..., 0.5922, 0.5882, 0.5804],
         ...,
         [0.6275, 0.6275, 0.6235,  ..., 0.3608, 0.6196, 0.6157],
         [0.6275, 0.6275, 0.6235,  ..., 0.5765, 0.6275, 0.5961],
         [0.6275, 0.6275, 0.6235,  ..., 0.6275, 0.6235, 0.6314]],

        [[0.9137, 0.9137, 0.9137,  ..., 0.9176, 0.9098, 0.8980],
         [0.9176, 0.9176, 0.9176,  ..., 0.9176, 0.9098, 0.8980],
         [0.9216, 0.9216, 0.9216,  ..., 0.9137, 0.9098, 0.

img_tensor: Default is (3, H, W)

In [13]:
writer.add_image("ToTensor",img_tensor)

In [11]:
trans_normalize1 = transforms.Normalize([0.5,0.5,0.5],[0.5,0.5,0.5])
trans_normalize2 = transforms.Normalize([100,5,66],[7,0.5,0.5])
img_norm1 = trans_normalize1(img_tensor)
img_norm2 = trans_normalize2(img_tensor)

In [ ]:
writer.add_image("Normalize", img_norm1, 0)
writer.add_image("Normalize", img_norm2, 1)


In [ ]:
trans_resize_1 = transforms.Resize((512,512))
img_resize_1 = trans_resize_1(img_tensor)
img_resize_1

tensor([[[0.3137, 0.3142, 0.3172,  ..., 0.3137, 0.3150, 0.3025],
         [0.3176, 0.3176, 0.3176,  ..., 0.3115, 0.3146, 0.3025],
         [0.3216, 0.3211, 0.3181,  ..., 0.3076, 0.3120, 0.3049],
         ...,
         [0.3412, 0.3386, 0.3373,  ..., 0.0214, 0.2205, 0.3603],
         [0.3412, 0.3386, 0.3373,  ..., 0.3481, 0.3381, 0.3382],
         [0.3412, 0.3386, 0.3373,  ..., 0.3538, 0.3142, 0.3206]],

        [[0.5922, 0.5926, 0.5956,  ..., 0.5922, 0.5935, 0.5809],
         [0.5961, 0.5961, 0.5961,  ..., 0.5900, 0.5930, 0.5809],
         [0.6000, 0.5996, 0.5965,  ..., 0.5861, 0.5904, 0.5833],
         ...,
         [0.6275, 0.6248, 0.6235,  ..., 0.1033, 0.4170, 0.6172],
         [0.6275, 0.6248, 0.6235,  ..., 0.5386, 0.5882, 0.6078],
         [0.6275, 0.6248, 0.6235,  ..., 0.6375, 0.6279, 0.6284]],

        [[0.9137, 0.9142, 0.9172,  ..., 0.9137, 0.9150, 0.9025],
         [0.9176, 0.9176, 0.9176,  ..., 0.9115, 0.9146, 0.9025],
         [0.9216, 0.9211, 0.9181,  ..., 0.9076, 0.9120, 0.

In [16]:
trans_resize_2 = transforms.Resize(512)
img_resize_2 = trans_resize_1(img_tensor)
img_resize_2

tensor([[[0.3137, 0.3142, 0.3172,  ..., 0.3137, 0.3150, 0.3025],
         [0.3176, 0.3176, 0.3176,  ..., 0.3115, 0.3146, 0.3025],
         [0.3216, 0.3211, 0.3181,  ..., 0.3076, 0.3120, 0.3049],
         ...,
         [0.3412, 0.3386, 0.3373,  ..., 0.0214, 0.2205, 0.3603],
         [0.3412, 0.3386, 0.3373,  ..., 0.3481, 0.3381, 0.3382],
         [0.3412, 0.3386, 0.3373,  ..., 0.3538, 0.3142, 0.3206]],

        [[0.5922, 0.5926, 0.5956,  ..., 0.5922, 0.5935, 0.5809],
         [0.5961, 0.5961, 0.5961,  ..., 0.5900, 0.5930, 0.5809],
         [0.6000, 0.5996, 0.5965,  ..., 0.5861, 0.5904, 0.5833],
         ...,
         [0.6275, 0.6248, 0.6235,  ..., 0.1033, 0.4170, 0.6172],
         [0.6275, 0.6248, 0.6235,  ..., 0.5386, 0.5882, 0.6078],
         [0.6275, 0.6248, 0.6235,  ..., 0.6375, 0.6279, 0.6284]],

        [[0.9137, 0.9142, 0.9172,  ..., 0.9137, 0.9150, 0.9025],
         [0.9176, 0.9176, 0.9176,  ..., 0.9115, 0.9146, 0.9025],
         [0.9216, 0.9211, 0.9181,  ..., 0.9076, 0.9120, 0.

In [ ]:
writer.add_image("resize",img_resize_1,1)
writer.add_image("resize",img_tensor,2)


In [19]:
trans_randomcrop = transforms.RandomCrop(512)
for i in range(15):
    writer.add_image("RandomCrop", trans_randomcrop(img_tensor), i)
writer.close()